name: Deploy main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo-compile-trad:
    runs-on: ubuntu-24.04
    steps:
    - name: "Demo: Build trad"
      uses: rimeinn/deploy-schema@master
      with:
        user-recipe-list: |-
          rimeinn/rime-moran@trad
        schema-list: |-
          moran
          moran_fixed
          moran_sentence
          moran_aux
        package-items: |-
          build
          lua
          opencc
          moran_custom_phrases.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: demo-trad.zip
        path: /tmp/deploy-schema/artifact.zip

  demo-compile-simp:
    runs-on: ubuntu-24.04
    steps:
    - name: "Demo: Build trad"
      uses: rimeinn/deploy-schema@master
      with:
        user-recipe-list: |-
          rimeinn/rime-moran@simp
        schema-list: |-
          moran
          moran_fixed
          moran_sentence
          moran_aux
        package-items: |-
          build
          lua
          opencc
          moran_custom_phrases.txt
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: demo-simp.zip
        path: /tmp/deploy-schema/artifact.zip

  build:
    needs: [demo-compile-trad, demo-compile-simp]
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Install dependencies
      run: sudo apt-get install -y opencc && pnpm install
    - name: Build VitePress
      run: pnpm simplify && pnpm build
    - name: Deploy
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr
        path: .vitepress/dist/
        remote_path: ${{ vars.DEPLOY_PATH }}
        remote_host: ${{ vars.DEPLOY_HOST }}
        remote_user: ${{ vars.DEPLOY_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
